version: 0.2

phases:
  pre_build:
    commands:
    - echo PRE BUILD PHASE
    - echo $dockerpass | docker login --username $dockeruser --password-stdin 
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - ls
      - cd mysql
      - docker build -t kiruthik-mysql-image .
      - cd ..
      - cd php
      - ls
      - docker build -t kiruthik-apache-image .
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s5o7d0z2
      - docker tag kiruthik-mysql-image public.ecr.aws/s5o7d0z2/kj-php-app:kiruthik-mysql-image
      - docker tag kiruthik-apache-image public.ecr.aws/s5o7d0z2/kj-php-app:kiruthik-apache-image
      - docker push public.ecr.aws/s5o7d0z2/kj-php-app:kiruthik-mysql-image
      - docker push public.ecr.aws/s5o7d0z2/kj-php-app:kiruthik-apache-image

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...