version: 0.2
phases:
  pre_build:
    commands:
    - echo PRE BUILD PHASE
    # - echo $dockerpass | docker login --username $dockeruser --password-stdin 
  build:
    commands:
    - echo Build started on `date`
    - docker build -t mysqldockimage ./mysql
    - docker build -t phpimage --no-cache ./php
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s5o7d0z2
    - docker tag mysqldockimage public.ecr.aws/s5o7d0z2/kj-php-app/mysql
    - docker tag phpimage public.ecr.aws/s5o7d0z2/kj-php-app/php
    - docker push public.ecr.aws/s5o7d0z2/kj-php-app/php
    - docker push public.ecr.aws/s5o7d0z2/kj-php-app/mysql
  post_build:
    commands:
    - echo Build completed on `date`
