version: 0.2
phases:
  pre_build:
    commands:
    - echo PRE BUILD PHASE
    - echo $dockerpass | docker login --username $dockeruser --password-stdin 
  build:
    commands:
    - echo Build started on `date`
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s5o7d0z2
    - docker build -t mysqldockimage ./mysql
    - docker tag mysqldockimage:latest public.ecr.aws/s5o7d0z2/kj-php-app:mysql
    - docker push public.ecr.aws/s5o7d0z2/kj-php-app:mysql
    - docker build -t phpimage --no-cache ./php
    - docker tag phpimage:latest public.ecr.aws/s5o7d0z2/kj-php-app:php
    - docker push public.ecr.aws/s5o7d0z2/kj-php-app:php
    
  post_build:
    commands:
    - echo Build completed on `date`
